/* KYE ROOM — content. Правьте тексты и цены здесь, разметку трогать не нужно.
   models — общее описание и прайс модели.
   items  — карточки каталога: одна карточка = один кадр = один вариант ткани. */

window.KYE = {

  ui: {
    ru: {
      nav_about: "Бренд", nav_craft: "Производство", nav_catalog: "Каталог", nav_contact: "Контакты",
      scroll: "Листайте", loading: "Загрузка",
      catalog_title: "Каталог",
      catalog_note: "Один силуэт живёт в нескольких тканях и каждая со своим характером.",
      view_nature: "На природе", view_room: "В интерьере",
      back: "К каталогу",
      sizes: "Размеры и стоимость", details: "Характеристики",
      request: "Оставить заявку",
      custom: "Возможен индивидуальный подбор ткани и размеров.",
      no_mattress: "Стоимость указана без матраса. При необходимости матрас можно приобрести отдельно.",
      lift_yes: "Подъёмный механизм предусмотрен.",
      lift_no: "Подъёмный механизм для этой модели не предусмотрен.",
      other: "Другие ткани этой модели",
      photo_hint: "Место под фото<br>основателей за работой",
      form_name: "Имя", form_phone: "Телефон", form_msg: "Модель, размер, ткань",
      form_send: "Отправить", form_ok: "Спасибо. Мы свяжемся с вами в течение дня.",
      c_show_v: "Шоурум по записи · ежедневно 11:00 — 20:00",
      c_ship_v: "Доставка по Казахстану и СНГ · сборка на месте"
    },
    kz: {
      nav_about: "Бренд", nav_craft: "Өндіріс", nav_catalog: "Каталог", nav_contact: "Байланыс",
      scroll: "Төмен", loading: "Жүктелуде",
      catalog_title: "Каталог",
      catalog_note: "Бір силуэт бірнеше матада өмір сүреді және әрқайсысының өз мінезі бар.",
      view_nature: "Табиғатта", view_room: "Интерьерде",
      back: "Каталогқа",
      sizes: "Өлшемдері мен бағасы", details: "Сипаттамасы",
      request: "Өтінім қалдыру",
      custom: "Мата мен өлшемді жеке тапсырыспен таңдауға болады.",
      no_mattress: "Баға матрассыз көрсетілген. Қажет болса, матрасты бөлек алуға болады.",
      lift_yes: "Көтергіш механизм қарастырылған.",
      lift_no: "Бұл модельге көтергіш механизм қарастырылмаған.",
      other: "Осы модельдің басқа маталары",
      photo_hint: "Құрылтайшылардың жұмыс үстіндегі<br>фотосына арналған орын",
      form_name: "Аты", form_phone: "Телефон", form_msg: "Модель, өлшем, мата",
      form_send: "Жіберу", form_ok: "Рақмет. Күн ішінде сізбен хабарласамыз.",
      c_show_v: "Шоурум алдын ала жазылу бойынша · күн сайын 11:00 — 20:00",
      c_ship_v: "Қазақстан және ТМД бойынша жеткізу · орнында жинау"
    },
    es: {
      nav_about: "Marca", nav_craft: "Taller", nav_catalog: "Catálogo", nav_contact: "Contacto",
      scroll: "Desliza", loading: "Cargando",
      catalog_title: "Catálogo",
      catalog_note: "Una misma silueta vive en varias telas y cada una tiene su propio carácter.",
      view_nature: "En la naturaleza", view_room: "En un hogar",
      back: "Catálogo",
      sizes: "Medidas y precio", details: "Ficha técnica",
      request: "Solicitar información",
      custom: "Telas y medidas a medida bajo pedido.",
      no_mattress: "El precio no incluye el colchón. El colchón puede encargarse aparte.",
      lift_yes: "Incluye mecanismo elevable con canapé.",
      lift_no: "Este modelo no cuenta con mecanismo elevable.",
      other: "Otras telas de este modelo",
      photo_hint: "Espacio para la foto<br>de los fundadores trabajando",
      form_name: "Nombre", form_phone: "Teléfono", form_msg: "Modelo, medida, tela",
      form_send: "Enviar", form_ok: "Gracias. Le escribiremos a lo largo del día.",
      c_show_v: "Showroom con cita previa · todos los días de 11:00 a 20:00",
      c_ship_v: "Envío a Kazajistán y la CEI · montaje en destino"
    },
    en: {
      nav_about: "Brand", nav_craft: "Craft", nav_catalog: "Catalogue", nav_contact: "Contact",
      scroll: "Scroll", loading: "Loading",
      catalog_title: "Catalogue",
      catalog_note: "One silhouette lives in several cloths and each has its own character.",
      view_nature: "In the wild", view_room: "In a home",
      back: "Catalogue",
      sizes: "Sizes and price", details: "Specification",
      request: "Make an enquiry",
      custom: "Custom fabrics and dimensions available on request.",
      no_mattress: "Price excludes the mattress. A mattress can be ordered separately.",
      lift_yes: "Storage lift mechanism included.",
      lift_no: "No storage lift mechanism for this model.",
      other: "Other fabrics of this model",
      photo_hint: "Photo slot<br>founders at work",
      form_name: "Name", form_phone: "Phone", form_msg: "Model, size, fabric",
      form_send: "Send", form_ok: "Thank you. We will be in touch within a day.",
      c_show_v: "Showroom by appointment · daily 11:00 — 20:00",
      c_ship_v: "Delivery across Kazakhstan and the CIS · assembled on site"
    }
  },

  /* ---------- БРЕНД И ПРОИЗВОДСТВО ----------
     photos: пути к двум снимкам для каждого блока.
     Оставьте пустыми — покажется рамка-заглушка.
     Положите файлы, например, в media/story/ и укажите здесь:
       photos: ["media/story/brand-1.jpg", "media/story/brand-2.jpg"]        */
  story: [
    {
      id: "about",
      photos: ["media/story/brand-1.webp"],
      cta: "#catalog",
      kz: {
        eyebrow: "Бренд",
        title: "Жай жиһаз емес<br><em>өнер туындысы</em>",
        body: "KYE ROOM партиямен шығармайды. Әр кереует жалғыз дана болып туады: бөлменің өлшеміне, жарықтың мінезіне, иесінің әдетіне қарай. Мұндай заттар үйде айналасындағы жөндеуден де ұзақ тұрады.",
        cta: "Каталогты қарау"
      },
      es: {
        eyebrow: "Marca",
        title: "No es un mueble<br><em>es una obra de arte</em>",
        body: "KYE ROOM no fabrica series. Cada cama nace como pieza única: a la medida de la habitación, al carácter de su luz, a la costumbre de quien duerme en ella. Piezas así permanecen en la casa más que la reforma que las rodea.",
        cta: "Ver el catálogo"
      },
      ru: {
        eyebrow: "Бренд",
        title: "Не просто мебель<br><em>произведение искусства</em>",
        body: "KYE ROOM не выпускает партии. Каждая кровать рождается в единственном экземпляре: под размер комнаты, под характер света, под привычку хозяина. Такие вещи остаются в доме дольше, чем ремонт вокруг них.",
        cta: "Смотреть каталог"
      },
      en: {
        eyebrow: "Brand",
        title: "Not furniture<br><em>a work of art</em>",
        body: "KYE ROOM does not run batches. Every bed is made once: to the size of the room, to the character of its light, to the habits of the person sleeping in it. Pieces like these outlast the renovation around them.",
        cta: "See the catalogue"
      }
    },
    {
      id: "craft",
      photos: ["media/story/craft-1.webp", "media/story/craft-2.webp"],
      cta: "#contact",
      kz: {
        eyebrow: "Өндіріс",
        title: "Еуропа маталары<br><em>ЧПУ-мен кесілген қаңқа</em>",
        body: "Англия, Франция, Италия, Бельгия және Түркияның үздік мануфактуралары. Тек зығыр мен мақта: беріктік пен асыл фактура. Қаңқа ЧПУ-да миллиметрдің оннан бір бөлігіне дейінгі дәлдікпен кесіледі, қаптаманы алғашқы тігістен соңғысына дейін бір шебер жүргізеді. Маталар 40 000 Мартиндейл циклінен асады, конструкцияға — бес жыл кепілдік.",
        cta: "Өтінім қалдыру"
      },
      es: {
        eyebrow: "Taller",
        title: "Telas de Europa<br><em>estructura cortada a CNC</em>",
        body: "Inglaterra, Francia, Italia, Bélgica y las mejores manufacturas turcas. Solo lino y algodón: resistencia y un tacto noble. La estructura se corta a CNC con una precisión de una décima de milímetro y un mismo artesano lleva la tapicería de la primera costura a la última. Las telas superan los 40 000 ciclos Martindale y la estructura tiene cinco años de garantía.",
        cta: "Solicitar información"
      },
      ru: {
        eyebrow: "Производство",
        title: "Ткани из Европы<br><em>каркас на ЧПУ</em>",
        body: "Англия, Франция, Италия, Бельгия и лучшие турецкие мануфактуры. Только лён и хлопок: прочность и благородная фактура. Каркас режется на ЧПУ с точностью до десятой миллиметра, обивку от первого шва до последнего ведёт один мастер. Ткани держат от 40 000 циклов Мартиндейла, на конструкцию — пять лет гарантии.",
        cta: "Оставить заявку"
      },
      en: {
        eyebrow: "Craft",
        title: "European cloth<br><em>CNC-cut frame</em>",
        body: "England, France, Italy, Belgium and the best Turkish mills. Linen and cotton only: strength and a noble hand. The frame is CNC-cut to a tenth of a millimetre, and one craftsman carries the upholstery from first seam to last. Fabrics hold from 40,000 Martindale cycles, five years of structural warranty.",
        cta: "Make an enquiry"
      }
    }
  ],

  contact: { phone: "+7 702 199 09 95", tel: "+77021990995", instagram: "@kye.room", instagram_url: "https://instagram.com/kye.room" },

  /* ---------- МОДЕЛИ: общее описание и прайс ---------- */
  models: {
    mona: {
      name: "MONA", lift: false,
      prices: [["90 × 200","300 000"],["120 × 200","350 000"],["140 × 200","400 000"],["160 × 200","450 000"],["180 × 200","500 000"],["200 × 200","550 000"]],
      kz: { lead: "Тік арналардағы доға",
            text: "Бас жақтың тік арналары доғаны бір де бір қыртыссыз ұстап тұрады, жіңішке шие түсті кант оны сурет жақтауындай айналдырып өтеді, ал дөңгеленген цоколь бүкіл конструкцияны еденнен көтереді. Қос царга — сирек кездесетін шешім: салмақты өзіне алып, жылдар бойы кез келген сықырды жояды." },
      es: { lead: "Un arco sobre canales verticales",
            text: "Los canales verticales del cabecero sostienen el arco sin un solo pliegue, un ribete fino color cereza lo enmarca como a un cuadro y un zócalo redondeado levanta el conjunto del suelo. El doble larguero es poco habitual: asume la carga y elimina cualquier crujido durante años." },
      ru: { lead: "Арка на вертикальных каналах",
            text: "Вертикальные каналы изголовья держат арку без единой складки, тонкий вишнёвый кант обводит её как рама картину, а округлый цоколь поднимает всю конструкцию над полом. Двойная царга — редкость: она берёт на себя вес и убирает любой скрип на годы вперёд." },
      en: { lead: "An arch on vertical channels",
            text: "Vertical channels hold the arch without a single crease, a thin cherry trim frames it like a painting, and a rounded plinth lifts the whole thing off the floor. The double side rail is rare: it takes the load and removes every creak for years ahead." }
    },
    queen: {
      name: "QUEEN", lift: true,
      prices: [["90 × 200","300 000"],["120 × 200","350 000"],["140 × 200","400 000"],["160 × 200","450 000"],["180 × 200","500 000"],["200 × 200","550 000"]],
      kz: { lead: "Толық шеге қатары бар классика",
            text: "Биік доға, ойқасты жоталық және бүкіл периметр бойындағы жиһаз шегелерінің толық қатары — кереуетті өз жасынан үлкен көрсететін дәл сол деталь. Зығыр жарықты сіңіреді, шегелер оны жинайды: бас жақтың суреті таңнан кешке дейін өзгеріп отырады." },
      es: { lead: "Un clásico con tachuelas en todo el contorno",
            text: "Un arco alto, una cresta perfilada y una hilera completa de tachuelas a lo largo de todo el perímetro: el detalle que hace que esta cama parezca más antigua de lo que es. El lino apaga la luz y las tachuelas la recogen, así que el cabecero se lee distinto al amanecer y al anochecer." },
      ru: { lead: "Классика с полным рядом гвоздей",
            text: "Высокая арка, фигурный гребень и полный ряд мебельных гвоздей по всему периметру — та самая деталь, из-за которой кровать выглядит старше собственного возраста. Лён гасит свет, гвозди его собирают: рисунок изголовья меняется от утра к вечеру." },
      en: { lead: "A classic, studded all the way round",
            text: "A tall arch, a shaped crest and a full row of nailheads along the entire border — the detail that makes this bed look older than it is. Linen absorbs the light while the studs collect it, so the headboard reads differently at dawn and at dusk." }
    },
    tadj: {
      name: "TADJ", lift: true,
      prices: [["90 × 200","300 000"],["120 × 200","350 000"],["140 × 200","400 000"],["160 × 200","500 000"],["180 × 200","550 000"],["200 × 200","600 000"]],
      kz: { lead: "Ені бойынша құстары бар бақ",
            text: "Кереуеттің еніндей бұлт тәрізді бас жақ, оның бетінде — кілегей түсті зығырға басылған бұтақтар, гүлдер мен құстар. Бұл өрнек емес, сурет: бедер дәл ортаға қойылады және шеттерінен кесілмейді, сондықтан әр кереует жеке пішіледі." },
      es: { lead: "Un jardín con pájaros a todo lo ancho",
            text: "Un cabecero en forma de nube tan ancho como la cama, con ramas, flores y pájaros estampados sobre lino crudo. No es un motivo, es un cuadro: el estampado se centra y nunca se corta en los bordes, por eso cada cama se despieza de forma individual." },
      ru: { lead: "Сад с птицами во всю ширину",
            text: "Изголовье-облако шириной во всю кровать, а на нём — ветви, цветы и птицы, набитые на кремовый лён. Это не орнамент, а картина: рисунок ставится по центру и не режется по краям, поэтому каждая кровать раскраивается индивидуально." },
      en: { lead: "A garden with birds, full width",
            text: "A cloud-shaped headboard as wide as the bed, carrying branches, blossom and perched birds printed on cream linen. This is a picture, not a pattern: the print is centred and never cut at the edges, so every bed is laid out individually." }
    },
    blanca: {
      name: "BLANCA", lift: true,
      prices: [["90 × 200","300 000"],["120 × 200","350 000"],["140 × 200","400 000"],["160 × 200","450 000"],["180 × 200","500 000"],["200 × 200","550 000"]],
      kz: { lead: "Контрастты канты бар ойқасты доға",
            text: "Қатаң жолақты да, ірі гүлді де, сепия жапырақты да бірдей жақсы ұстайтын форма. Матаны ауыстырасыз — бүкіл бөлме өзгереді, ал қаңқа сол күйінде қалады. Төменгі бүрмесі қалауыңыз бойынша." },
      es: { lead: "Un arco perfilado con ribete en contraste",
            text: "Una forma que sostiene igual de bien una raya sobria, una flor grande o una hoja en sepia. Cambia la tela y cambia toda la habitación, mientras la estructura sigue siendo la misma. El faldón fruncido es opcional." },
      ru: { lead: "Фигурная арка с контрастным кантом",
            text: "Форма, которая одинаково хорошо держит и строгую полоску, и крупный цветок, и сепийный лист. Меняете ткань — меняется вся комната, при том что каркас остаётся тем же. Оборка по низу опциональна." },
      en: { lead: "A shaped arch with contrast piping",
            text: "A form that carries a quiet stripe, a large floral and a sepia leaf print equally well. Change the cloth and the whole room changes, while the frame stays exactly the same. The gathered skirt is optional." }
    },
    luma: {
      name: "LUMA", lift: true,
      prices: [["90 × 200","300 000"],["120 × 200","350 000"],["140 × 200","400 000"],["160 × 200","450 000"],["180 × 200","500 000"],["200 × 200","550 000"]],
      kz: { lead: "Бөлмені ұстап тұратын түс",
            text: "Үстіне гүл шашылған қою көгілдір — қанық түсті кереует қабырғалармен таласпай, оларды өз айналасына жинайтын сирек жағдай. Ойқасты жоталық түстің салмағын жұмсартады, ал ашық түсті негіз конструкцияны көзге ауыр көрсетпейді." },
      es: { lead: "Un color que sostiene la habitación",
            text: "Un turquesa oscuro salpicado de flores: el caso poco frecuente en que una cama saturada no discute con las paredes, sino que las reúne a su alrededor. La cresta perfilada suaviza el peso del color y la base clara evita que el conjunto se vea pesado." },
      ru: { lead: "Цвет, который держит комнату",
            text: "Тёмная бирюза с рассыпанным по ней цветком — редкий случай, когда насыщенная кровать не спорит со стенами, а собирает их вокруг себя. Фигурный гребень смягчает вес цвета, а светлое основание не даёт конструкции просесть визуально." },
      en: { lead: "A colour that holds the room",
            text: "Dark teal scattered with flowers — the rare case where a saturated bed does not argue with the walls but gathers them around itself. The shaped crest softens the weight of the colour, and the pale base keeps the whole piece from sitting heavy." }
    },
    moon: {
      name: "MOON", lift: true,
      prices: [["160 × 200","500 000"],["180 × 200","550 000"],["200 × 200","600 000"]],
      kz: { lead: "Валик үстінде валик, артық ештеңе жоқ",
            text: "Каталогтағы ең тыныш модель: аласа әрі кең платформа, бас жақтың орнына — бірінің үстіне бірі жатқан вельветтен жасалған екі валик. Ешқандай ою жоқ, кант жоқ. Тек фактура жұмыс істейді: қырлы бедер жарықты іліп алып, қабырға бойымен көлденең жолақ салады." },
      es: { lead: "Rulo sobre rulo, nada más",
            text: "La pieza más silenciosa del catálogo: una plataforma baja y ancha y, en lugar de cabecero, dos rulos de pana apoyados uno sobre otro. Sin talla, sin ribete. Aquí solo trabaja la textura: la canaleta atrapa la luz y dibuja una línea horizontal a lo largo de la pared." },
      ru: { lead: "Валик на валике, ничего лишнего",
            text: "Самая тихая модель в каталоге: низкая широкая платформа, а вместо изголовья — два валика из вельвета, лежащие друг на друге. Никакой резьбы, никакого канта. Работает только фактура: рубчик ловит свет и рисует горизонтальную полосу через всю стену." },
      en: { lead: "Bolster on bolster, nothing else",
            text: "The quietest piece in the catalogue: a low wide platform and, instead of a headboard, two corduroy bolsters resting on one another. No carving, no piping. Only texture works here — the rib catches light and draws a horizontal line across the wall." }
    },
    ostin: {
      name: "OSTIN", lift: true,
      prices: [["140 × 200","400 000"],["160 × 200","450 000"],["180 × 200","500 000"],["200 × 200","550 000"]],
      kz: { lead: "Күрделі сызық, қарапайым отырыс",
            text: "Коллекциядағы ең суретті контур: жоталық толқынмен жүріп, иыққа құлайды да, жіңішке кантпен қайтып оралады. Сонымен бірге кереует аласа әрі тұруға ыңғайлы күйінде қалады — бүкіл күрделілік габаритке емес, силуэтке кеткен." },
      es: { lead: "Una línea compleja, un asiento sencillo",
            text: "El contorno más dibujado de la colección: la cresta avanza en onda, cae en los hombros y vuelve convertida en un ribete fino. Aun así la cama se mantiene baja y cómoda para levantarse: toda la complejidad se fue a la silueta y ninguna al volumen." },
      ru: { lead: "Сложная линия, простая посадка",
            text: "Самый рисованный контур в коллекции: гребень идёт волной, срывается в плечи и возвращается тонким кантом. При этом кровать остаётся низкой и удобной для подъёма — вся сложность ушла в силуэт, а не в габариты." },
      en: { lead: "A complex line, an easy sit",
            text: "The most drawn outline in the collection: the crest runs in a wave, breaks into shoulders and returns as a fine piping. The bed itself stays low and easy to get out of — all the complexity went into the silhouette, none into the bulk." }
    },
    west: {
      name: "WEST", lift: true,
      prices: [["90 × 200","300 000"],["120 × 200","350 000"],["140 × 200","380 000"],["160 × 200","450 000"],["180 × 200","500 000"],["200 × 200","550 000"]],
      kz: { lead: "Төбені жоғары тартатын жолақ",
            text: "Биік доға төбені көзге жиырма сантиметрдей көтереді — бұл тәсіл аласа жатын бөлмеде де жұмыс істейді. Негізі әдейі төмендетілген, сол себепті бүкіл салмақ жоғарыдан оқылады." },
      es: { lead: "Una raya que estira el techo",
            text: "El arco alto sube el techo unos veinte centímetros a la vista, un recurso que funciona incluso en un dormitorio bajo. La base se ha dejado deliberadamente rebajada para que todo el peso se lea arriba." },
      ru: { lead: "Полоска, которая тянет потолок вверх",
            text: "Высокая арка визуально поднимает потолок сантиметров на двадцать — приём, который работает даже в невысокой спальне. Основание намеренно занижено, чтобы весь вес читался наверху." },
      en: { lead: "A stripe that lifts the ceiling",
            text: "A tall arch visually raises the ceiling by twenty centimetres — a trick that works even in a low bedroom. The base is deliberately kept shallow so that all the weight reads at the top." }
    },
    san: {
      name: "SAN", lift: true,
      prices: [["140 × 200","400 000"],["160 × 200","450 000"],["180 × 200","500 000"],["200 × 200","550 000"]],
      kz: { lead: "Доғаның орнына жұмсақ толқын",
            text: "Жоталық шеттен шетке біркелкі толқынмен жүреді, оны ең жіңішке қою кант айналдырып өтеді — бүкіл жұмысты бір сызық атқарады. Мұндай бас жаққа не үстіндегі сурет, не бүйіріндегі бра керек емес: айналасындағы қабырға бос қалуы тиіс." },
      es: { lead: "Una onda suave en lugar de arco",
            text: "La cresta recorre la cama de lado a lado en una onda regular, perfilada por el ribete oscuro más fino: una sola línea hace todo el trabajo. Un cabecero así no necesita cuadros encima ni apliques a los lados: la pared a su alrededor debe quedarse vacía." },
      ru: { lead: "Мягкая волна вместо арки",
            text: "Гребень идёт ровной волной от края до края, обведённый тончайшим тёмным кантом — одна линия, которая делает всю работу. Такое изголовье не требует ни картин над кроватью, ни бра по бокам: стена вокруг него должна остаться пустой." },
      en: { lead: "A soft wave instead of an arch",
            text: "The crest runs edge to edge in an even wave, outlined by the finest dark piping — one line doing all the work. A headboard like this needs no pictures above it and no sconces beside it: the wall around it should stay empty." }
    },
    rumi: {
      name: "RUMI", lift: true,
      prices: [["140 × 200","400 000"],["160 × 200","450 000"],["180 × 200","500 000"],["200 × 200","550 000"]],
      kz: { lead: "Жоғарысы ашық, төменгісі қою",
            text: "Тәсіл қарапайым әрі мүлтіксіз: ашық түсті жолақты бас жақ пен терең түсті негіз. Кереует жиһаз болудан қалып, бүкіл жатын бөлме айналасына құрылатын түс дағына айналады." },
      es: { lead: "Claro arriba, denso abajo",
            text: "Un recurso sencillo e infalible: un cabecero claro a rayas sobre una base de color profundo. La cama deja de ser un mueble y se convierte en la mancha de color alrededor de la cual se construye todo el dormitorio." },
      ru: { lead: "Светлый верх, плотный низ",
            text: "Приём простой и безотказный: светлое изголовье в полоску и глубокое цветное основание. Кровать перестаёт быть мебелью и становится цветовым пятном, вокруг которого строится вся спальня." },
      en: { lead: "Pale above, dense below",
            text: "A simple, foolproof move: a pale striped headboard over a deep coloured base. The bed stops being furniture and becomes the block of colour the whole bedroom is built around." }
    },
    diva: {
      name: "DIVA", lift: true,
      prices: [["Высота на выбор","от 800 000"]],
      prices_en: [["Height to order","from 800 000"]],
      prices_kz: [["Биіктігі тапсырыс бойынша","800 000 ₸-ден бастап"]],
      prices_es: [["Altura a medida","desde 800 000"]],
      kz: { lead: "Қара жақтаудағы екі доға",
            text: "Коллекциядағы ең театрлы зат: гобеленмен қапталған, қара лакталған жақтаудағы екі биік доға. Биіктігі жеке есептеледі, баға да содан шығады. Төбесі аласа жатын бөлмеде бұл модель жұмыс істемейді — оған ауа керек." },
      es: { lead: "Dos arcos en un marco negro",
            text: "La pieza más teatral de la colección: dos arcos altos en un marco lacado en negro, tapizados en gobelino. La altura se calcula de forma individual y el precio va detrás. Este modelo no funciona bajo un techo bajo: necesita aire." },
      ru: { lead: "Две арки в чёрной раме",
            text: "Самая театральная вещь коллекции: две высокие арки в чёрной лакированной раме, затянутые гобеленом. Высота считается индивидуально, от неё же зависит цена. В спальне с низким потолком эта модель не работает — ей нужен воздух." },
      en: { lead: "Two arches in a black frame",
            text: "The most theatrical piece in the collection: two tall arches in a black lacquered frame, upholstered in tapestry. The height is calculated individually and the price follows it. This model does not work under a low ceiling; it needs air." }
    },
    love: {
      name: "LOVE", lift: true,
      prices: [["90 × 200","300 000"],["120 × 200","350 000"],["140 × 200","380 000"]],
      kz: { lead: "Симметрияны ұстайтын жұп",
            text: "Екеу болып тұру үшін ойластырылған бір орындық модель: шегелері бар екі бірдей доға және дәл ортадағы тумба. Қонақ бөлме, балалар бөлмесі, ата-анаға арналған бөлме — қатаң ось керек жердің бәрінде. Жекелей де алынады." },
      es: { lead: "Una pareja que sostiene el eje",
            text: "Una cama individual pensada para ir de dos en dos: dos arcos idénticos con tachuelas y una mesilla justo en el eje. Habitación de invitados, cuarto infantil, dormitorio para los padres: allí donde haga falta una simetría estricta. También funciona sola." },
      ru: { lead: "Пара, которая держит симметрию",
            text: "Односпальная модель, придуманная для того, чтобы стоять вдвоём: две одинаковые арки с гвоздями и тумба ровно по центру. Гостевая, детская, комната для родителей — везде, где нужна строгая ось. Берётся и поодиночке." },
      en: { lead: "A pair that holds the axis",
            text: "A single bed designed to stand in twos: two identical studded arches with a nightstand exactly on the centre line. Guest room, children's room, a room for parents — anywhere a strict axis is needed. Works alone as well." }
    },
    king: {
      name: "KING", lift: true,
      prices: [["90 × 200","380 000"],["120 × 200","450 000"],["140 × 200","500 000"]],
      kz: { lead: "Жасылмен айналдырылған бал түсті жолақ",
            text: "Бал-кілегей жолақтағы жоталықтың кең толқыны қою жасыл кантпен айналдырылған — әдетте жиһаз салондарында емес, ескі ағылшын үйлерінде кездесетін үйлесім. Бүйірлері көтерілген, сондықтан кереует күндізгі кушетка болып оқылады." },
      es: { lead: "Una raya miel perfilada en verde",
            text: "La amplia onda de la cresta en una raya miel y crema, perfilada en verde oscuro: una combinación que suele encontrarse en casas inglesas antiguas antes que en tiendas de muebles. Los laterales están elevados, así que la pieza se lee como un diván de día." },
      ru: { lead: "Медовая полоска, обведённая зелёным",
            text: "Широкая волна гребня в медово-кремовой полоске, обведённая тёмно-зелёным кантом — сочетание, которое обычно встречается в старых английских домах, а не в мебельных салонах. Боковины подняты, поэтому кровать читается как дневная кушетка." },
      en: { lead: "A honey stripe outlined in green",
            text: "A wide wave of a crest in a honey-and-cream stripe, outlined in dark green — a combination usually found in old English houses rather than furniture showrooms. The sides are raised, so the piece reads as a daybed." }
    },
    pink: {
      name: "PINK", lift: true,
      prices: [["90 × 200","450 000"],["120 × 200","500 000"],["140 × 200","550 000"]],
      kz: { lead: "Балалар бөлмесіндегі алғашқы ересек зат",
            text: "Ойқасты бүйірлері мен арқасы бар кушетка, қызғылт-ақ жолақты, әр қырында ақ канты бар. Ересек жиһаз сияқты жасалған: сол қаңқа, сол маталар, сол жинақ — тек басқа масштабта. Бүйір бортиктері жеткілікті биік, қосымша қою қажет емес." },
      es: { lead: "El primer mueble adulto de un cuarto infantil",
            text: "Un diván con laterales y respaldo perfilados, a rayas rosa y blanco, ribeteado en blanco en cada canto. Está hecho como mueble de adulto: la misma estructura, las mismas telas, el mismo montaje, solo que a otra escala. Los laterales son lo bastante altos como para no añadir barrera." },
      ru: { lead: "Первая взрослая вещь в детской",
            text: "Кушетка с фигурными боковинами и спинкой, в розово-белую полоску с белым кантом по каждому ребру. Сделана как взрослая мебель: тот же каркас, те же ткани, та же сборка — просто в другом масштабе. Бортики достаточно высокие, чтобы не ставить дополнительные." },
      en: { lead: "The first grown-up piece in a child's room",
            text: "A daybed with shaped sides and back in a pink-and-white stripe, piped in white along every edge. Built like adult furniture: same frame, same fabrics, same assembly — simply at another scale. The sides are high enough that no extra rail is needed." }
    },
    pouf: {
      name: "POUF", display: { ru: "ПУФЫ", en: "OTTOMANS", kz: "ПУФТАР", es: "PUFS" }, lift: null,
      prices: [["Пуфы и банкетки","80 000 — 150 000"]],
      prices_en: [["Ottomans and benches","80 000 — 150 000"]],
      prices_kz: [["Пуфтар мен банкеткалар","80 000 — 150 000"]],
      prices_es: [["Pufs y banquetas","80 000 — 150 000"]],
      kz: { lead: "Мінезді ұстап тұратын ұсақ зат",
            text: "Пуфтар мен банкеткалар кереуеттерге кететін сол еуропалық маталардың қалдықтарынан жиналады — сондықтан бір пуф ешқашан дерлік қайталанбайды. Барқыт, букле, шашақ, ағаш және шар тәріздес аяқтар. Бағасы өлшемге, матаға және күрделілікке байланысты." },
      es: { lead: "El detalle pequeño que marca el tono",
            text: "Los pufs y las banquetas se hacen con los retales de las mismas telas europeas que van a las camas, por eso un puf casi nunca se repite. Terciopelo, bouclé, flecos, patas de madera y patas de bola. El precio depende del tamaño, la tela y la complejidad." },
      ru: { lead: "Мелочь, которая держит характер",
            text: "Пуфы и банкетки собираются из остатков тех же европейских тканей, что идут на кровати, — поэтому один пуф почти никогда не повторяется. Бархат, букле, бахрома, деревянные и шаровые опоры. Стоимость зависит от размера, ткани и сложности." },
      en: { lead: "The small thing that sets the tone",
            text: "Ottomans and benches are made from the offcuts of the same European cloth that goes into the beds — which is why a stool is almost never repeated. Velvet, boucle, fringe, wooden and ball feet. Price depends on size, fabric and complexity." }
    },
    pillow: {
      name: "PILLOW", display: { ru: "ПОДУШКИ", en: "CUSHIONS", kz: "ЖАСТЫҚТАР", es: "COJINES" }, lift: null,
      prices: [["Декоративные подушки","10 000 — 30 000"]],
      prices_en: [["Decorative cushions","10 000 — 30 000"]],
      prices_kz: [["Сәндік жастықтар","10 000 — 30 000"]],
      prices_es: [["Cojines decorativos","10 000 — 30 000"]],
      kz: { lead: "Соңғы қабат",
            text: "Нақты кереуетке арналған сәндік жастықтар мен валиктер: бедерін, тығыздығы мен пішінін бас жақпен таласпай, оны жалғастыратындай етіп таңдаймыз. Монограмма, кант, шашақ, дөңгелек ұштар — таңдауыңыз бойынша." },
      es: { lead: "La última capa",
            text: "Cojines y rulos decorativos hechos para una cama concreta: elegimos el dibujo, la densidad y la forma para que continúen el cabecero en lugar de discutir con él. Monograma, ribete, flecos, remates redondos: usted decide." },
      ru: { lead: "Последний слой",
            text: "Декоративные подушки и валики под конкретную кровать: подбираем рисунок, плотность и форму так, чтобы они не спорили с изголовьем, а продолжали его. Монограмма, кант, бахрома, круглые торцы — по вашему выбору." },
      en: { lead: "The final layer",
            text: "Decorative cushions and bolsters made for a specific bed: we choose the pattern, the density and the shape so that they continue the headboard rather than argue with it. Monogram, piping, fringe, round end caps — your call." }
    }
  },

  /* ---------- КАРТОЧКИ КАТАЛОГА: одна карточка = один кадр ----------
     scene — описание сцены для генерации кадра. На сайте не выводится,
     лежит здесь как памятка, если снимок понадобится переснять. */
  items: [
    { id:"mona-ivory", model:"mona",
      es:{ variant:"Marfil", note:"Doble larguero, zócalo de nogal",
           scene:"Una meseta seca en septiembre: el atardecer vuelve el nogal casi rojo y calienta la tela acanalada." },
      kz:{ variant:"Піл сүйегі", note:"Қос царга, жаңғақ цоколь",
           scene:"Қыркүйектегі құрғақ үстірт: батар күн жаңғақты қызылға бояп, арналы қаптаманы жылытады." },
      ru:{ variant:"Слоновая кость", note:"Двойная царга, ореховый цоколь",
           scene:"Сухое плато в сентябре: закат делает орех почти красным, а канальную обивку — тёплой." },
      en:{ variant:"Ivory", note:"Double side rail, walnut plinth",
           scene:"A dry September plateau: the sunset turns the walnut almost red and warms the channelled cloth." } },

    { id:"mona-terra", model:"mona",
      es:{ variant:"Terracota", note:"Base de terciopelo, cabecero a rayas",
           scene:"Arenisca roja al atardecer: la base de terciopelo y la roca comparten un mismo pigmento." },
      kz:{ variant:"Терракота", note:"Барқыт негіз, жолақты бас жақ",
           scene:"Батар күндегі қызыл құмтас — негіздің барқыты мен жыныс бір пигментте." },
      ru:{ variant:"Терракота", note:"Бархатное основание, полосатое изголовье",
           scene:"Красный песчаник на закате — бархат основания и порода одного пигмента." },
      en:{ variant:"Terracotta", note:"Velvet base, striped headboard",
           scene:"Red sandstone at sunset — the velvet base and the rock share one pigment." } },

    { id:"queen", model:"queen",
      es:{ variant:"Lino crudo", note:"Hilera completa de tachuelas",
           scene:"La orilla de un lago de montaña entre niebla al amanecer, donde la ropa blanca brilla por sí sola." },
      kz:{ variant:"Кілегей зығыр", note:"Жиһаз шегелерінің толық қатары",
           scene:"Таң сәріде тұманға оранған тау көлінің жағасы, ақ төсек-орын өздігінен жарқырайды." },
      ru:{ variant:"Кремовый лён", note:"Полный ряд мебельных гвоздей",
           scene:"Берег горного озера в тумане на рассвете, где белое бельё светится само по себе." },
      en:{ variant:"Cream linen", note:"Full nailhead border",
           scene:"A misty mountain lakeshore at dawn, where white bedding glows on its own." } },

    { id:"tadj", model:"tadj",
      es:{ variant:"Chinoiserie", note:"Cresta de nube, estampado colocado a mano",
           scene:"Un lago alpino a la hora azul: el agua ha extraído todo el azul del estampado." },
      kz:{ variant:"Шинуазри", note:"Бұлт жоталық, принтті қолмен жаю",
           scene:"Көк сағаттағы альпі көлі — су принттен барлық көкті тартып алған." },
      ru:{ variant:"Шинуазри", note:"Облачный гребень, ручная раскладка принта",
           scene:"Альпийское озеро в синий час — вода вытянула из принта весь синий." },
      en:{ variant:"Chinoiserie", note:"Cloud crest, hand-laid print",
           scene:"An alpine lake at blue hour — the water pulled every blue out of the print." } },

    { id:"blanca-terra", model:"blanca",
      es:{ variant:"Terracota", note:"Raya con base de terciopelo",
           scene:"Badlands de arcilla al atardecer: la luz lateral dura esculpe las crestas y el zócalo." },
      kz:{ variant:"Терракота", note:"Жолақ және барқыт негіз",
           scene:"Батар күндегі саз бедленд: қатты бүйір жарық қабатты жоталар мен цокольді мүсіндейді." },
      ru:{ variant:"Терракота", note:"Полоска и бархатное основание",
           scene:"Глиняные бэдлендс на закате: жёсткий боковой свет лепит слоистые гряды и цоколь." },
      en:{ variant:"Terracotta", note:"Stripe with a velvet base",
           scene:"Clay badlands at sunset: hard side light sculpts the layered ridges and the plinth." } },

    { id:"blanca-powder", model:"blanca",
      es:{ variant:"Flor empolvada", note:"Estampado melocotón, ribete a juego",
           scene:"Un campo de peonías al amanecer: el fondo continúa literalmente el dibujo de la tela." },
      kz:{ variant:"Опа түсті гүл", note:"Шабдалы принт, түстес кант",
           scene:"Таң сәріндегі пион алқабы — фон матаның бедерін тікелей жалғастырады." },
      ru:{ variant:"Пудровый цветок", note:"Персиковый принт, кант в тон",
           scene:"Поле пионов на рассвете — фон буквально продолжает рисунок ткани." },
      en:{ variant:"Powder floral", note:"Peach print, matching piping",
           scene:"A peony field at sunrise — the background is literally a continuation of the cloth." } },

    { id:"blanca-sepia", model:"blanca",
      es:{ variant:"Sepia", note:"Hoja grande, ropa de cama oliva",
           scene:"Un hayedo en noviembre: la hojarasca de cobre en el mismo sepia que la tapicería." },
      kz:{ variant:"Сепия", note:"Ірі жапырақ, зәйтүн төсек-орын",
           scene:"Қарашадағы бук орманы: мыс түсті төсеніш пен қаптамадағы дәл сол сепия." },
      ru:{ variant:"Сепия", note:"Крупный лист, оливковое бельё",
           scene:"Буковый лес в ноябре: медная подстилка и та же сепия, что на обивке." },
      en:{ variant:"Sepia", note:"Large leaf print, olive bedding",
           scene:"A beech forest in November: copper leaf litter in the same sepia as the upholstery." } },

    { id:"luma-teal", model:"luma",
      es:{ variant:"Turquesa", note:"Estampado floral sobre fondo oscuro",
           scene:"Un desfiladero de helechos con cascada: la piedra mojada tiene la misma profundidad que la tela." },
      kz:{ variant:"Көгілдір", note:"Қою өрістегі гүл принті",
           scene:"Сарқырамасы бар папоротник шатқалы — дымқыл тас матамен бірдей тереңдікті ұстайды." },
      ru:{ variant:"Бирюза", note:"Цветочный принт по тёмному полю",
           scene:"Папоротниковый каньон с водопадом — мокрый камень держит ту же глубину, что и ткань." },
      en:{ variant:"Teal", note:"Floral print on a dark ground",
           scene:"A fern gorge with a waterfall — wet stone holds the same depth as the cloth." } },

    { id:"luma-night", model:"luma",
      es:{ variant:"Turquesa noche", note:"Acentos rojos en el estampado",
           scene:"Un lago oscuro de bosque al amanecer saca el rojo del estampado." },
      kz:{ variant:"Түнгі көгілдір", note:"Принттегі қызыл екпіндер",
           scene:"Таң сәріндегі қараңғы орман көлі принттен қызылды тартып шығарады." },
      ru:{ variant:"Ночная бирюза", note:"Красные акценты в принте",
           scene:"Тёмное лесное озеро на рассвете вытягивает из принта красное." },
      en:{ variant:"Night teal", note:"Red accents in the print",
           scene:"A dark forest lake at dawn draws the red out of the print." } },

    { id:"moon", model:"moon",
      es:{ variant:"Pana oliva", note:"Plataforma baja, dos rulos",
           scene:"Un claro de musgo en un bosque viejo, donde mejor se lee la horizontal de la plataforma." },
      kz:{ variant:"Зәйтүн вельвет", note:"Аласа платформа, екі валик",
           scene:"Ескі ормандағы мүкті алаң, платформаның көлденеңі ең жақсы осында оқылады." },
      ru:{ variant:"Оливковый вельвет", note:"Низкая платформа, два валика",
           scene:"Мшистая поляна в старом лесу, где горизонталь платформы читается лучше всего." },
      en:{ variant:"Olive corduroy", note:"Low platform, two bolsters",
           scene:"A mossy clearing in an old forest, where the platform's horizontal reads best." } },

    { id:"ostin-milk", model:"ostin",
      es:{ variant:"Leche", note:"Cresta perfilada, ribete oscuro",
           scene:"Caliza blanca a mediodía: un monocromo donde solo trabaja la silueta." },
      kz:{ variant:"Сүт түсті", note:"Ойқасты жоталық, қою кант",
           scene:"Түс кезіндегі ақ әктас: тек силуэт жұмыс істейтін монохром." },
      ru:{ variant:"Молочный", note:"Фигурный гребень, тёмный кант",
           scene:"Белый известняк в полдень: монохром, где работает только силуэт изголовья." },
      en:{ variant:"Milk", note:"Shaped crest, dark piping",
           scene:"White limestone at noon: a monochrome where only the silhouette works." } },

    { id:"ostin-mustard", model:"ostin",
      es:{ variant:"Mostaza", note:"Flor gráfica sobre amarillo",
           scene:"Colza en flor al atardecer: un mismo pigmento del primer plano al horizonte." },
      kz:{ variant:"Қыша", note:"Сарыға салынған графикалық гүл",
           scene:"Батар күндегі гүлдеген рапс — алдыңғы шептен көкжиекке дейін бір пигмент." },
      ru:{ variant:"Горчица", note:"Графичный цветок по жёлтому",
           scene:"Цветущий рапс на закате — один пигмент от переднего плана до горизонта." },
      en:{ variant:"Mustard", note:"Graphic floral on yellow",
           scene:"Rapeseed in flower at sunset — one pigment from foreground to horizon." } },

    { id:"west", model:"west",
      es:{ variant:"Raya rosa", note:"Arco alto, base rebajada",
           scene:"Un prado alpino al amanecer, sobre un mar de niebla en el valle." },
      kz:{ variant:"Қызғылт жолақ", note:"Биік доға, төмендетілген негіз",
           scene:"Күн шыға бердегі альпі шалғыны, аңғардағы тұман теңізінің үстінде." },
      ru:{ variant:"Розовая полоска", note:"Высокая арка, заниженное основание",
           scene:"Альпийский луг на восходе, над морем тумана в долине." },
      en:{ variant:"Blush stripe", note:"Tall arch, shallow base",
           scene:"An alpine meadow at sunrise, above a sea of fog in the valley." } },

    { id:"san-dune", model:"san",
      es:{ variant:"Duna", note:"Manta y rulo en terracota",
           scene:"Una duna al atardecer: las ondas de arena repiten la misma onda que la cresta." },
      kz:{ variant:"Дюна", note:"Терракота плед пен валик",
           scene:"Батар күндегі құм төбе: құм толқыны жоталықтың дәл сол толқынын қайталайды." },
      ru:{ variant:"Дюна", note:"Терракотовый плед и валик",
           scene:"Дюна на закате: рябь песка повторяет ту же волну, что и гребень." },
      en:{ variant:"Dune", note:"Terracotta throw and bolster",
           scene:"A dune at sunset: the sand ripples repeat the same wave as the crest." } },

    { id:"san-salt", model:"san",
      es:{ variant:"Sal", note:"Crudo liso, ropa de cama blanca",
           scene:"Un salar convertido en espejo: minimalismo donde la onda es el único acento." },
      kz:{ variant:"Тұз", note:"Таза кілегей, ақ төсек-орын",
           scene:"Су айнасы бар сор — бас жақтың толқыны жалғыз екпін болатын минимализм." },
      ru:{ variant:"Соль", note:"Чистый кремовый, белое бельё",
           scene:"Солончак с зеркалом воды — минимализм, где волна изголовья единственный акцент." },
      en:{ variant:"Salt", note:"Plain cream, white bedding",
           scene:"A mirrored salt flat — minimalism where the wave is the only accent." } },

    { id:"rumi-wine", model:"rumi",
      es:{ variant:"Vino", note:"Base de terciopelo, arco a rayas",
           scene:"Un viñedo de otoño al atardecer: las hileras funcionan como líneas de fuga hacia el cabecero." },
      kz:{ variant:"Шарап түсті", note:"Барқыт негіз, жолақты доға",
           scene:"Батар күндегі күзгі жүзімдік: жүзім қатарлары бас жаққа апаратын перспектива сызығы." },
      ru:{ variant:"Винный", note:"Бархатное основание, полосатая арка",
           scene:"Осенний виноградник на закате: ряды лоз работают перспективными линиями к изголовью." },
      en:{ variant:"Wine", note:"Velvet base, striped arch",
           scene:"An autumn vineyard at sunset: the rows work as leading lines to the headboard." } },

    { id:"rumi-indigo", model:"rumi",
      es:{ variant:"Índigo", note:"Base azul, dibujo tonal",
           scene:"Arena mojada a la orilla del océano al atardecer: el contraste de color más fuerte de la colección." },
      kz:{ variant:"Индиго", note:"Көк негіз, тондық бедер",
           scene:"Батар күндегі мұхит жағасының дымқыл құмы — коллекциядағы ең күшті түс контрасты." },
      ru:{ variant:"Индиго", note:"Синее основание, тональный рисунок",
           scene:"Мокрый песок у океана на закате — самый сильный цветовой контраст в коллекции." },
      en:{ variant:"Indigo", note:"Blue base, tonal pattern",
           scene:"Wet sand at the ocean's edge at sunset — the strongest colour contrast in the collection." } },

    { id:"diva-indienne", model:"diva",
      es:{ variant:"Indiana", note:"Gobelino rojo, marco lacado en negro",
           scene:"Un cañón rojo: las paredes sostienen el cabecero alto y un haz de luz hace de foco." },
      kz:{ variant:"Индиенна", note:"Қызыл гобелен, қара лакталған жақтау",
           scene:"Қызыл шатқал: қабырғалар биік бас жақты тіреп тұр, жарық сәулесі софит рөлінде." },
      ru:{ variant:"Индиенна", note:"Красный гобелен, чёрная лакированная рама",
           scene:"Красный каньон: стены подпирают высокое изголовье, луч света работает как софит." },
      en:{ variant:"Indienne", note:"Red tapestry, black lacquered frame",
           scene:"A red canyon: the walls support the tall headboard and a shaft of light acts as a spotlight." } },

    { id:"diva-green", model:"diva",
      es:{ variant:"Gobelino verde", note:"Dibujo botánico, banqueta a juego",
           scene:"Una espesura de abetos con rayos por detrás: el gobelino verde es el bosque." },
      kz:{ variant:"Жасыл гобелен", note:"Ботаникалық бедер, түстес банкетка",
           scene:"Артынан сәуле түскен шырша қалыңдығы — жасыл гобеленнің өзі орман." },
      ru:{ variant:"Зелёный гобелен", note:"Ботанический рисунок, банкетка в тон",
           scene:"Еловая чаща с лучами сзади — зелёный гобелен и есть лес." },
      en:{ variant:"Green tapestry", note:"Botanical print, matching bench",
           scene:"A fir thicket with rays behind — the green tapestry is the forest." } },

    { id:"love", model:"love",
      es:{ variant:"Pareja empolvada", note:"Dos individuales con mesilla en el eje",
           scene:"Un bosque de abedules al amanecer, donde los troncos marcan el mismo ritmo vertical." },
      kz:{ variant:"Опа түсті жұп", note:"Екі бір орындық және ортадағы тумба",
           scene:"Таң сәріндегі қайың тоғайы, дің дәл сол тік ырғақты береді." },
      ru:{ variant:"Пудровая пара", note:"Две односпальных и тумба по центру",
           scene:"Берёзовая роща на рассвете, где стволы задают тот же вертикальный ритм." },
      en:{ variant:"Blush pair", note:"Two singles with a nightstand on the axis",
           scene:"A birch grove at dawn, where the trunks set the same vertical rhythm." } },

    { id:"king", model:"king",
      es:{ variant:"Raya miel", note:"Ribete verde, laterales elevados",
           scene:"Trigo maduro a contraluz, donde la miel y el verde se encuentran solos." },
      kz:{ variant:"Бал жолақ", note:"Жасыл кант, көтерілген бүйірлер",
           scene:"Қарсы жарықтағы піскен бидай, бал мен жасыл өздігінен түйіседі." },
      ru:{ variant:"Медовая полоска", note:"Зелёный кант, поднятые боковины",
           scene:"Спелая пшеница на контровом свете, где медовый и зелёный сходятся сами собой." },
      en:{ variant:"Honey stripe", note:"Green piping, raised sides",
           scene:"Ripe wheat against the light, where honey and green meet on their own." } },

    { id:"pink", model:"pink",
      es:{ variant:"Raya rosa", note:"Diván con laterales perfilados",
           scene:"Un cerezo en flor, donde el rosa está en la tela y en el aire por igual." },
      kz:{ variant:"Қызғылт жолақ", note:"Ойқасты бүйірлері бар кушетка",
           scene:"Гүлдеген шие бағы, қызғылт матада да, ауада да бар." },
      ru:{ variant:"Розовая полоска", note:"Кушетка с фигурными боковинами",
           scene:"Цветущий вишнёвый сад, где розовый есть и на ткани, и в воздухе." },
      en:{ variant:"Pink stripe", note:"Daybed with shaped sides",
           scene:"A cherry orchard in bloom, where the pink is in the cloth and in the air alike." } },

    { id:"pouf-set", model:"pouf",
      es:{ variant:"La colección", note:"Terciopelo, bouclé, flecos",
           scene:"Una ladera de hierba a la hora dorada: los pufs se alzan como rocas y las sombras se alargan a la derecha." },
      kz:{ variant:"Коллекция", note:"Барқыт, букле, шашақ",
           scene:"Батар күндегі шөпті беткей: пуфтар тас сияқты тізілген, көлеңкелер оңға созылады." },
      ru:{ variant:"Коллекция", note:"Бархат, букле, бахрома",
           scene:"Травяной склон на закате: пуфы расставлены как валуны, тени тянутся вправо." },
      en:{ variant:"The set", note:"Velvet, boucle, fringe",
           scene:"A grassy slope at golden hour: the stools stand like boulders, shadows raking right." } },

    { id:"pouf-poppy", model:"pouf",
      es:{ variant:"Amapola", note:"Bouclé rojo, patas de bola",
           scene:"Un campo de amapolas: un mismo color en dos texturas, un teleobjetivo separa el puf del fondo." },
      kz:{ variant:"Көкнәр", note:"Қызыл букле, шар аяқтар",
           scene:"Көкнәр даласы: екі фактурадағы бір түс, ұзын фокус пуфты фоннан бөліп тұр." },
      ru:{ variant:"Маковый", note:"Красное букле, шаровые опоры",
           scene:"Маковое поле: один цвет в двух фактурах, длинный фокус отделяет пуф от фона." },
      en:{ variant:"Poppy", note:"Red boucle, ball feet",
           scene:"A poppy field: one colour in two textures, a long lens separating stool from ground." } },

    { id:"pillow", model:"pillow",
      es:{ variant:"Terracota", note:"Rulos con flecos y ribete",
           scene:"Un alerzal a finales de otoño: las acículas oxidadas repiten el color de las telas." },
      kz:{ variant:"Терракота", note:"Шашағы мен канты бар валиктер",
           scene:"Күздің соңындағы балқарағай орманы — тат түсті инелер маталардың түсін қайталайды." },
      ru:{ variant:"Терракота", note:"Валики с бахромой и кантом",
           scene:"Лиственничный лес поздней осенью — ржавая хвоя повторяет цвет тканей." },
      en:{ variant:"Terracotta", note:"Bolsters with fringe and piping",
           scene:"A larch forest in late autumn — rust needles echo the colour of the cloth." } }
  ]
};
